In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df = df.iloc[:,2:]

In [5]:
df.sample(5)

     Age  EstimatedSalary  Purchased
151   41            45000          0
312   38            50000          0
29    31            18000          0
93    29            28000          0
134   28            55000          0